package net.flinkgutt.samples.nodes.dbmanager;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.swing.DefaultEventListModel;
import ca.odell.glazedlists.swing.GlazedListsSwing;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.DefaultComboBoxModel;
import net.flinkgutt.samples.nodes.api.db.IConnectionService;
import net.flinkgutt.samples.nodes.api.db.IDatabaseServer;
import net.flinkgutt.samples.nodes.api.db.IDatabaseServerSettings;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Exceptions;
import org.openide.util.ImageUtilities;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;

/**
 *
 * @author Christian
 */
public class ConnectionManager extends javax.swing.JPanel {

    public static final String CONFIGURATION_NODE_NAME = "netbeans-samples_servers";
    private IConnectionService service = Lookup.getDefault().lookup(IConnectionService.class);
    private List<IDatabaseServer> databaseServers = new ArrayList<IDatabaseServer>();
    private EventList<IDatabaseServerSettings> settingsEventList = new BasicEventList<IDatabaseServerSettings>();
    private DefaultEventListModel<IDatabaseServerSettings> settingsModel = GlazedListsSwing.eventListModel(settingsEventList);
    private static final Logger LOG = Logger.getLogger(ConnectionManager.class.getName());

    /**
     * Creates new form ConnectionManager
     */
    public ConnectionManager() {
        initComponents();

        // TODO This needs to be less hardcoded and coupled up with what's happening in SuperDAO and the registered SQL drivers.
        IDatabaseServer mysql = new DBServer("MySQL", "org.gjt.mm.mysql.Driver", "3306", "jdbc:mysql://", "com.mysql");
        IDatabaseServer postgresql = new DBServer("PostgreSQL", "org.postgresql.Driver", "5432", "jdbc:postgresql://", "org.postgresql");
        databaseServers.add(mysql);
        databaseServers.add(postgresql);
        databaseServerComboBox.setModel(new DefaultComboBoxModel<IDatabaseServer>(databaseServers.toArray(new IDatabaseServer[databaseServers.size()])));
        try {
            getConfiguredServers();
        } catch (BackingStoreException ex) {
            Exceptions.printStackTrace(ex);
            // TODO Show some dialog to the user that tells them the PreferenceStore is unavailable, in different and prettier words
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverListScrollPane = new javax.swing.JScrollPane();
        serverJList = new javax.swing.JList<IDatabaseServerSettings>();
        serversLabel = new javax.swing.JLabel();
        settingsTabbedPane1 = new javax.swing.JTabbedPane();
        dbSettingsPanel = new javax.swing.JPanel();
        databaseServerComboBox = new javax.swing.JComboBox<IDatabaseServer>();
        sqlServerLabel = new javax.swing.JLabel();
        hostnameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        hostnameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        databaseLabel = new javax.swing.JLabel();
        dbPortLabel = new javax.swing.JLabel();
        dbPortField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        databaseField = new javax.swing.JTextField();
        connectionNameLable = new javax.swing.JLabel();
        connectionNameField = new javax.swing.JTextField();
        testConnectionButton = new javax.swing.JButton();
        sshTunnelPanel = new javax.swing.JPanel();
        useSSHTunnelCheckbox = new javax.swing.JCheckBox();
        sshTunnelExplainLabel = new javax.swing.JLabel();
        sshHostIpLabel = new javax.swing.JLabel();
        sshHostnameField = new javax.swing.JTextField();
        sshPortLabel = new javax.swing.JLabel();
        sshPortSpinner = new javax.swing.JSpinner();
        sshUsernameLabel = new javax.swing.JLabel();
        sshUsernameField = new javax.swing.JTextField();
        sshPasswordLabel = new javax.swing.JLabel();
        sshPasswordField = new javax.swing.JPasswordField();
        connectButton = new javax.swing.JButton();
        addServerButton = new javax.swing.JButton();
        saveServerSettingButton = new javax.swing.JButton();
        removeServerButton = new javax.swing.JButton();

        serverJList.setModel(settingsModel);
        serverJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        serverJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                serverJListValueChanged(evt);
            }
        });
        serverListScrollPane.setViewportView(serverJList);

        serversLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(serversLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.serversLabel.text")); // NOI18N

        databaseServerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseServerComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(sqlServerLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sqlServerLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hostnameLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.hostnameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(usernameLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.usernameLabel.text")); // NOI18N

        hostnameField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.hostnameField.text")); // NOI18N

        usernameField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.usernameField.text")); // NOI18N

        passwordField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.passwordField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.passwordLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(databaseLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.databaseLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbPortLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.dbPortLabel.text")); // NOI18N

        dbPortField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.dbPortField.text")); // NOI18N

        databaseField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.databaseField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(connectionNameLable, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connectionNameLable.text")); // NOI18N

        connectionNameField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connectionNameField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(testConnectionButton, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.testConnectionButton.text")); // NOI18N
        testConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testConnectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbSettingsPanelLayout = new javax.swing.GroupLayout(dbSettingsPanel);
        dbSettingsPanel.setLayout(dbSettingsPanelLayout);
        dbSettingsPanelLayout.setHorizontalGroup(
            dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(databaseLabel)
                                    .addComponent(hostnameLabel)
                                    .addComponent(sqlServerLabel)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(databaseServerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                                        .addComponent(hostnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dbPortLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dbPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(databaseField)
                                    .addComponent(usernameField)
                                    .addComponent(passwordField))
                                .addGap(0, 47, Short.MAX_VALUE))
                            .addComponent(jSeparator1)))
                    .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                        .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(connectionNameLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(connectionNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dbSettingsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(testConnectionButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dbSettingsPanelLayout.setVerticalGroup(
            dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectionNameLable)
                    .addComponent(connectionNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqlServerLabel)
                    .addComponent(databaseServerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostnameLabel)
                    .addComponent(hostnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbPortLabel)
                    .addComponent(dbPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseLabel)
                    .addComponent(databaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(testConnectionButton)
                .addContainerGap())
        );

        settingsTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.dbSettingsPanel.TabConstraints.tabTitle"), dbSettingsPanel); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(useSSHTunnelCheckbox, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.useSSHTunnelCheckbox.text")); // NOI18N
        useSSHTunnelCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSSHTunnelCheckboxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(sshTunnelExplainLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshTunnelExplainLabel.text")); // NOI18N
        sshTunnelExplainLabel.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(sshHostIpLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshHostIpLabel.text")); // NOI18N
        sshHostIpLabel.setEnabled(false);

        sshHostnameField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshHostnameField.text")); // NOI18N
        sshHostnameField.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(sshPortLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshPortLabel.text")); // NOI18N
        sshPortLabel.setEnabled(false);

        sshPortSpinner.setModel(new javax.swing.SpinnerNumberModel(22, 1, 65556, 1));
        sshPortSpinner.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(sshUsernameLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshUsernameLabel.text")); // NOI18N
        sshUsernameLabel.setEnabled(false);

        sshUsernameField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshUsernameField.text")); // NOI18N
        sshUsernameField.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(sshPasswordLabel, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshPasswordLabel.text")); // NOI18N
        sshPasswordLabel.setEnabled(false);

        sshPasswordField.setText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshPasswordField.text")); // NOI18N
        sshPasswordField.setEnabled(false);

        javax.swing.GroupLayout sshTunnelPanelLayout = new javax.swing.GroupLayout(sshTunnelPanel);
        sshTunnelPanel.setLayout(sshTunnelPanelLayout);
        sshTunnelPanelLayout.setHorizontalGroup(
            sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sshTunnelPanelLayout.createSequentialGroup()
                .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sshTunnelPanelLayout.createSequentialGroup()
                        .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sshTunnelPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(sshPasswordLabel))
                            .addGroup(sshTunnelPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sshPortLabel)
                                    .addComponent(sshHostIpLabel)
                                    .addComponent(sshUsernameLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sshHostnameField)
                            .addComponent(sshUsernameField)
                            .addComponent(sshPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addGroup(sshTunnelPanelLayout.createSequentialGroup()
                                .addComponent(sshPortSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(sshTunnelPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useSSHTunnelCheckbox)
                            .addComponent(sshTunnelExplainLabel))))
                .addContainerGap())
        );
        sshTunnelPanelLayout.setVerticalGroup(
            sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sshTunnelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useSSHTunnelCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sshTunnelExplainLabel)
                .addGap(18, 18, 18)
                .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sshHostnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sshHostIpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sshPortLabel)
                    .addComponent(sshPortSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sshUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sshUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sshTunnelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sshPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sshPasswordLabel))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        settingsTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.sshTunnelPanel.TabConstraints.tabTitle"), sshTunnelPanel); // NOI18N

        connectButton.setIcon(ImageUtilities.loadImageIcon("net/flinkgutt/samples/nodes/dbmanager/1369435792_connect_creating.png",false));
        org.openide.awt.Mnemonics.setLocalizedText(connectButton, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connectButton.text")); // NOI18N
        connectButton.setToolTipText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connectButton.toolTipText")); // NOI18N
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        addServerButton.setIcon(ImageUtilities.loadImageIcon("net/flinkgutt/samples/nodes/dbmanager/1369435396_db_add.png", false));
        org.openide.awt.Mnemonics.setLocalizedText(addServerButton, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.addServerButton.text")); // NOI18N
        addServerButton.setToolTipText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.addServerButton.toolTipText")); // NOI18N
        addServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServerButtonActionPerformed(evt);
            }
        });

        saveServerSettingButton.setIcon(ImageUtilities.loadImageIcon("net/flinkgutt/samples/nodes/dbmanager/1369435663_3floppy_unmount.png",false));
        org.openide.awt.Mnemonics.setLocalizedText(saveServerSettingButton, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.saveServerSettingButton.text")); // NOI18N
        saveServerSettingButton.setToolTipText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.saveServerSettingButton.toolTipText")); // NOI18N
        saveServerSettingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveServerSettingButtonActionPerformed(evt);
            }
        });

        removeServerButton.setIcon(ImageUtilities.loadImageIcon("net/flinkgutt/samples/nodes/dbmanager/1369435531_db_remove.png", false));
        org.openide.awt.Mnemonics.setLocalizedText(removeServerButton, org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.removeServerButton.text")); // NOI18N
        removeServerButton.setToolTipText(org.openide.util.NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.removeServerButton.toolTipText")); // NOI18N
        removeServerButton.setEnabled(false);
        removeServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeServerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(serverListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serversLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(saveServerSettingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addServerButton, removeServerButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(serversLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsTabbedPane1)
                    .addComponent(serverListScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addServerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeServerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveServerSettingButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(connectButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(2, 2, 2))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addServerButton, connectButton, removeServerButton, saveServerSettingButton});

    }// </editor-fold>//GEN-END:initComponents

    private void useSSHTunnelCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSSHTunnelCheckboxActionPerformed
        boolean isChecked = useSSHTunnelCheckbox.isSelected();
        sshTunnelExplainLabel.setEnabled(isChecked);
        sshHostIpLabel.setEnabled(isChecked);
        sshHostnameField.setEnabled(isChecked);
        sshPortLabel.setEnabled(isChecked);
        sshPortSpinner.setEnabled(isChecked);
        sshUsernameField.setEnabled(isChecked);
        sshUsernameLabel.setEnabled(isChecked);
        sshPasswordField.setEnabled(isChecked);
        sshPasswordLabel.setEnabled(isChecked);
    }//GEN-LAST:event_useSSHTunnelCheckboxActionPerformed

    private void testConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testConnectionButtonActionPerformed
        // TODO Check if everything we need is filled out properly

        boolean clearToConnectToDB = true;
        // If this connection is to use an SSH tunnel to get to the DB
        if (useSSHTunnelCheckbox.isSelected()) {
            // TODO Implement setup of tunnel
            // some check to see if the tunnel is up and running
            // set clearToConnectToDB = false if the tunnel isn't open
            clearToConnectToDB = false;
        }
        // TODO Add some testing/validation of the parameters to the connection attempt.
        IDatabaseServer testServer = (IDatabaseServer) databaseServerComboBox.getSelectedItem();
        String dbUrl = testServer.getConnectionString() + hostnameField.getText() + ":" + dbPortField.getText() + "/" + databaseField.getText();
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());

        // if the attempt to create a tunnel failed or some validation (TODO) fails on username, password, servername, port etc.
        if(!clearToConnectToDB) {
            return;
        }
        
        Connection connection = null;
        boolean success = true;
        String errorMessage = "";
        try {
            Class.forName(testServer.getDriverUrl());
            connection = DriverManager.getConnection(dbUrl,
                    username, password);
            connection.setAutoCommit(false);
        } catch (SQLException ex) {
            /*
             ** "Connect error"...
             */
            success = false;
            errorMessage = ex.getMessage();
        } catch (java.lang.ClassNotFoundException ex) {
            /*
             ** "Driver error"...
             */
            success = false;
            errorMessage = ex.getMessage();
        } finally {
            if (null != connection) {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        }

        if (success) {
            NotifyDescriptor nd = new NotifyDescriptor.Message(NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connect.success"), NotifyDescriptor.INFORMATION_MESSAGE);
            DialogDisplayer.getDefault().notifyLater(nd);
        } else {
            NotifyDescriptor nd = new NotifyDescriptor.Message(NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connect.failure", errorMessage), NotifyDescriptor.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notifyLater(nd);
        }
    }//GEN-LAST:event_testConnectionButtonActionPerformed
    private int getIndexOfServer(IDatabaseServerSettings server) {
        if (server == null) {
            return -1;
        }
        for (int i = 0; i < settingsEventList.size(); i++) {
            IDatabaseServerSettings serv = settingsEventList.get(i);
            if (server.getStoredID().equals(serv.getStoredID())) {
                return i;
            }
        }
        return -1;
    }
    private void serverJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_serverJListValueChanged

        if (serverJList.isSelectionEmpty()) {
            removeServerButton.setEnabled(false);
            return;
        }
        removeServerButton.setEnabled(true);
        // Temporarily storing the settings filled out in the view in the associated object
        int index = getIndexOfServer(currentSettings);
        if (currentSettings != null && index >= 0) {
            ((DBServerSettings) currentSettings).setDisplayName(connectionNameField.getText());
            ((DBServerSettings) currentSettings).setDbName(databaseField.getText());
            ((DBServerSettings) currentSettings).setDBHostname(hostnameField.getText());
            ((DBServerSettings) currentSettings).setDBPort(Integer.parseInt(dbPortField.getText()));
            ((DBServerSettings) currentSettings).setDbPassword(new String(passwordField.getPassword()));
            ((DBServerSettings) currentSettings).setDbUsername(usernameField.getText());

            ((DBServerSettings) currentSettings).setSSHHostname(sshHostnameField.getText());
            ((DBServerSettings) currentSettings).setSSHPassword(new String(sshPasswordField.getPassword()));
            ((DBServerSettings) currentSettings).setSSHPort((Integer) sshPortSpinner.getValue());
            ((DBServerSettings) currentSettings).setSSHUsername(sshUsernameField.getText());
            ((DBServerSettings) currentSettings).setUseTunnel(useSSHTunnelCheckbox.isSelected());
            this.settingsEventList.set(index, currentSettings);
        }

        currentSettings = serverJList.getSelectedValue();
        connectionNameField.setText(currentSettings.getDisplayName());
        databaseField.setText(currentSettings.getDBName());
        hostnameField.setText(currentSettings.getDBHostname());
        dbPortField.setText("" + currentSettings.getDBPort());
        passwordField.setText(currentSettings.getDBPassword());
        usernameField.setText(currentSettings.getDBUsername());

        sshHostnameField.setText(currentSettings.getSSHHostname());
        sshPasswordField.setText(currentSettings.getSSHPassword());
        sshPortSpinner.setValue(currentSettings.getSSHPort());
        sshUsernameField.setText(currentSettings.getSSHUsername());
        useSSHTunnelCheckbox.setSelected(currentSettings.useTunnel());

        String identifier = currentSettings.getDBIdentifier();
        if (identifier == null) {
            databaseServerComboBox.setSelectedIndex(0);
            return;
        }
        // Setting the correct database server in the combobox
        int itemCount = databaseServerComboBox.getItemCount();
        for (int i = 0; i < itemCount; i++) {
            IDatabaseServer server = databaseServerComboBox.getItemAt(i);
            if (identifier.equals(server.getIdentifier())) {
                databaseServerComboBox.setSelectedIndex(i);
            }
        }

    }//GEN-LAST:event_serverJListValueChanged

    private void databaseServerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseServerComboBoxActionPerformed
        IDatabaseServer databaseServer = (IDatabaseServer) databaseServerComboBox.getSelectedItem();
        dbPortField.setText(databaseServer.getDefaultPort());

    }//GEN-LAST:event_databaseServerComboBoxActionPerformed
    private IDatabaseServerSettings currentSettings = null;
    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        saveServerSettingButtonActionPerformed(null);
        currentSettings = serverJList.getSelectedValue();
        if (currentSettings != null) {
            boolean isUp = false;
            String errorMessage = "";
            try {
                isUp = service.connect(currentSettings);
            } catch (Exception e) { // This is bad, don't do this.
                errorMessage = e.getMessage();
                LOG.log(Level.SEVERE, "Error during either connection to server or during DB creation.", e);
            }
            NotifyDescriptor nd;
            if (isUp) {
                nd = new NotifyDescriptor.Message(NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connect.success"), NotifyDescriptor.INFORMATION_MESSAGE);
            } else {
                nd = new NotifyDescriptor.Message(NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.connect.failure", errorMessage), NotifyDescriptor.ERROR_MESSAGE);
            }
            DialogDisplayer.getDefault().notify(nd);
        }
    }//GEN-LAST:event_connectButtonActionPerformed
    private int newServerCounter = 1;
    private void addServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServerButtonActionPerformed
        // Adds an empty server settings object to the ServerJList
        DBServerSettings newServer = new DBServerSettings();
        newServer.setDisplayName(NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.newServerDisplayName.text", newServerCounter++));
        newServer.setStorageID("DBSERVER-" + System.currentTimeMillis());
        newServer.setSSHPort(22); // Just so it's set to the default value that's the most common.
        settingsEventList.add(newServer);
        serverJList.setSelectedValue(newServer, true);
    }//GEN-LAST:event_addServerButtonActionPerformed

    private void saveServerSettingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveServerSettingButtonActionPerformed
        // Saves the currently selected servers settings
        if (currentSettings == null) {
            return;
        }
        ((DBServerSettings) currentSettings).setDisplayName(connectionNameField.getText());
        // DB specific settings
        ((DBServerSettings) currentSettings).setDbName(databaseField.getText());
        ((DBServerSettings) currentSettings).setDBHostname(hostnameField.getText());
        ((DBServerSettings) currentSettings).setDBPort(Integer.parseInt(dbPortField.getText()));
        ((DBServerSettings) currentSettings).setDbPassword(new String(passwordField.getPassword()));
        ((DBServerSettings) currentSettings).setDbUsername(usernameField.getText());
        // SSH Specpfic settings
        ((DBServerSettings) currentSettings).setSSHHostname(sshHostnameField.getText());
        ((DBServerSettings) currentSettings).setSSHPassword(new String(sshPasswordField.getPassword()));
        ((DBServerSettings) currentSettings).setSSHUsername(sshUsernameField.getText());
        ((DBServerSettings) currentSettings).setUseTunnel(useSSHTunnelCheckbox.isSelected());
        ((DBServerSettings) currentSettings).setSSHPort((Integer) sshPortSpinner.getValue());

        // Database Server stuff (i.e. MySQL, PostgreSQL)
        IDatabaseServer server = (IDatabaseServer) databaseServerComboBox.getSelectedItem();
        ((DBServerSettings) currentSettings).setDriver(server.getDriverUrl());
        ((DBServerSettings) currentSettings).setJDBCString(server.getConnectionString());
        ((DBServerSettings) currentSettings).setDBIdentifier(server.getIdentifier());

        storeServer(currentSettings);
    }//GEN-LAST:event_saveServerSettingButtonActionPerformed

    // Removes the currently selected server from the list and the backing datastore
    private void removeServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeServerButtonActionPerformed
        NotifyDescriptor nd = new NotifyDescriptor.Confirmation(NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.removeServer.confirmation.body", currentSettings.getDisplayName()), NbBundle.getMessage(ConnectionManager.class, "ConnectionManager.removeServer.confirmation.title"),
                NotifyDescriptor.QUESTION_MESSAGE);
        DialogDisplayer.getDefault().notify(nd);

        if (nd.getValue() != NotifyDescriptor.OK_OPTION) {
            // We do nothing because the user opted not to remove the selected server
            // This get's called if we hit cancel or close the dialog (hit the x)
            return;
        }
        // We remove the server
        settingsEventList.remove(currentSettings);

        Preferences configNode = NbPreferences.root().node(CONFIGURATION_NODE_NAME).node(currentSettings.getStoredID());
        try {
            configNode.removeNode();
            configNode.flush();
        } catch (BackingStoreException ex) {
            Exceptions.printStackTrace(ex);
        }
        // Clear the fields so we're ready to enter a new server
        clearFields();

    }//GEN-LAST:event_removeServerButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServerButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextField connectionNameField;
    private javax.swing.JLabel connectionNameLable;
    private javax.swing.JTextField databaseField;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JComboBox<IDatabaseServer> databaseServerComboBox;
    private javax.swing.JTextField dbPortField;
    private javax.swing.JLabel dbPortLabel;
    private javax.swing.JPanel dbSettingsPanel;
    private javax.swing.JTextField hostnameField;
    private javax.swing.JLabel hostnameLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton removeServerButton;
    private javax.swing.JButton saveServerSettingButton;
    private javax.swing.JList<IDatabaseServerSettings> serverJList;
    private javax.swing.JScrollPane serverListScrollPane;
    private javax.swing.JLabel serversLabel;
    private javax.swing.JTabbedPane settingsTabbedPane1;
    private javax.swing.JLabel sqlServerLabel;
    private javax.swing.JLabel sshHostIpLabel;
    private javax.swing.JTextField sshHostnameField;
    private javax.swing.JPasswordField sshPasswordField;
    private javax.swing.JLabel sshPasswordLabel;
    private javax.swing.JLabel sshPortLabel;
    private javax.swing.JSpinner sshPortSpinner;
    private javax.swing.JLabel sshTunnelExplainLabel;
    private javax.swing.JPanel sshTunnelPanel;
    private javax.swing.JTextField sshUsernameField;
    private javax.swing.JLabel sshUsernameLabel;
    private javax.swing.JButton testConnectionButton;
    private javax.swing.JCheckBox useSSHTunnelCheckbox;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    private void storeServer(IDatabaseServerSettings s) {
        // Just so we have something to test with for the time being
        Preferences servers = NbPreferences.root().node(CONFIGURATION_NODE_NAME);

        String storedId = s.getStoredID();

        Preferences settings = servers.node(storedId);
        settings.put("displayname", s.getDisplayName());
        settings.put("dbhostname", s.getDBHostname());
        settings.put("dbusername", s.getDBUsername());
        settings.put("dbpassword", s.getDBPassword());
        settings.put("dbname", s.getDBName());
        settings.putInt("dbport", s.getDBPort());
        settings.putBoolean("useTunnel", s.useTunnel());

        settings.put("dbidentifier", s.getDBIdentifier());
        settings.put("jdbcurl", s.getJDBCString());
        settings.put("dbdriver", s.getDriver());
        try {
            servers.flush();
        } catch (BackingStoreException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    private void getConfiguredServers() throws BackingStoreException {
        List<IDatabaseServerSettings> serverList = new ArrayList<IDatabaseServerSettings>();

        Preferences servers = NbPreferences.root().node(CONFIGURATION_NODE_NAME);
        if (servers != null) {
            String[] dbservers = servers.childrenNames();
            for (int i = 0; i < dbservers.length; i++) {
                String specificServer = dbservers[i];
                if (specificServer.startsWith("DBSERVER-")) {
                    Preferences s = servers.node(specificServer);
                    DBServerSettings se = new DBServerSettings();
                    // DB and Connection settings
                    se.setDisplayName(s.get("displayname", ""));
                    se.setDBHostname(s.get("dbhostname", ""));
                    se.setDBPort(s.getInt("dbport", 0));
                    se.setDbName(s.get("dbname", ""));
                    se.setDbUsername(s.get("dbusername", ""));
                    se.setDbPassword(s.get("dbpassword", ""));
                    // DB and Storage settings 
                    se.setStorageID(specificServer);
                    se.setDBIdentifier(s.get("dbidentifier", ""));
                    se.setDriver(s.get("dbdriver", ""));
                    se.setJDBCString(s.get("jdbcurl", ""));
                    // SSH specific settings
                    se.setUseTunnel(s.getBoolean("usetunnel", false));
                    se.setSSHHostname(s.get("sshhostname", ""));
                    se.setSSHUsername(s.get("sshusername", ""));
                    se.setSSHPort(s.getInt("sshport", 22));

                    serverList.add(se);
                }
            }
        }
        settingsEventList.clear();
        settingsEventList.addAll(serverList);
    }
    // Clear out the fields in the panels

    private void clearFields() {
        connectionNameField.setText("");
        databaseField.setText("");
        hostnameField.setText("");
        dbPortField.setText("" + "");
        passwordField.setText("");
        usernameField.setText("");

        sshHostnameField.setText("");
        sshPasswordField.setText("");
        sshPortSpinner.setValue(22);
        sshUsernameField.setText("");
        useSSHTunnelCheckbox.setSelected(false);
    }
}
